# Generated by Django 6.1 on 2026-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_rooms/'),
        ),
    ]
