# Generated by Django 6.1.1 on 2026-10-01 08:01

from django.db import migrations, models


def mark_recorded_messages(apps, schema_editor):
    """Отмечает ранее записанные в чате голосовые и видео.

    Такие файлы клиент называет voice_message_* / video_message_*,
    поэтому старые записи восстанавливаются по имени вложения.
    """

    Message = apps.get_model('chat', 'Message')

    Message.objects.filter(
        attachment_name__startswith='voice_message_',
    ).update(recorded=True)

    Message.objects.filter(
        attachment_name__startswith='video_message_',
    ).update(recorded=True)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_recorded_messages,
            migrations.RunPython.noop,
        ),
    ]
